### ISSUE TITLE
Support AzureOpenAI client 

### ISSUE THREAD

**Issue by codelion** [codelion/optillm#13]
As mentioned in #11 it should be easy to support base models that are deployed on azure by passing the `AzureOpenAI` client instead of the default one.

**Comment by virtualramblas** [comment]
Thank you for opening this issue. I have raised pull request #18 for it. Motivated by the fact that I don't have an OpenAI key, but I have one for Azure :) 
Thanks @codelion  for creating this wonderful project :clap:
