### ISSUE TITLE
Flask import fails

### ISSUE THREAD

**Issue by vanetreg** [codelion/optillm#23]
After installing optillm from reqs and testing it, I got error:
Traceback (most recent call last):
```
  File "***\optillm\optillm.py", line 5, in <module>       
    from flask import Flask, request, jsonify
ModuleNotFoundError: No module named 'flask'
```
Using "pip list", it lists "Flask" (**capital F**)
so  pls. fix it.

**Comment by codelion** [comment]
I don't understand the issue? The import is [correct](https://github.com/pallets/flask/?tab=readme-ov-file#a-simple-example), did you install the dependencies?

**Comment by vanetreg** [comment]
> I don't understand the issue? The import is [correct](https://github.com/pallets/flask/?tab=readme-ov-file#a-simple-example), did you install the dependencies?

Yes I did, using
`pip install -r requirements.txt`
I meant this when writing:
"After installing optillm from reqs",
doing it in a new branch of your repo.

**Comment by codelion** [comment]
Did you create a virtual environment before installing?

Are you on python3? What do you get when you run the following in your terminal?

```
(.venv) codelion@Asankhayas-MBP optillm % python --version
Python 3.12.5
(.venv) codelion@Asankhayas-MBP optillm % pip --version   
pip 24.0 from /Users/codelion/Documents/GitHub/optillm/.venv/lib/python3.12/site-packages/pip (python 3.12)
```

**Comment by vanetreg** [comment]
Yes, I created venv before installing it in the new branch.
I'm on Windows 10.
```
(optillm-venv) PS D:\***\optillm> python -c "import sys; print(sys.version)"
3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
(optillm-venv) PS D:\***\optillm>    python -m pip --version  
pip 23.3.1 from C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)
```

**Comment by vanetreg** [comment]
I created and using a new venv for the new branch and it works this way.
