### ISSUE TITLE
Possible error in calculate_confidence() logic for cot_decoding.py

### ISSUE THREAD

**Issue by jovanwongzixi** [codelion/optillm#45]
Hello,

Thanks for providing a great open-source implementation of the CoT Decoding technique published by DeepMind. However, I noticed a possible error in calculation of confidence level in the calculate_confidence() function in [cot_decoding.py](https://github.com/codelion/optillm/blob/main/optillm/cot_decoding.py). I think the error lies in prob.size() using dimension 0, instead of -1.

When I tested out the code on my notebook, the confidence score always returns a value of 1 regardless of what message I pass in under user prompt. I ran the experiment on a jupyter notebook using the exact same code from [cot_decoding.py](https://github.com/codelion/optillm/blob/main/optillm/cot_decoding.py) with the Qwen2.5-0.5B-Instruct model from Huggingface.

Below is a screenshot showing some of the possible answer texts and their respective confidence score, which is always 1. In this case I used the "Was Nicolas Cage born in an even or odd year?" prompt provided in the Google DeepMind example.

![image](https://github.com/user-attachments/assets/4cc756d6-a9ad-4428-8417-77f8f84c1faf)

I found that prob.size() in calculate_confidence should use the dimension -1 instead of 0, as prob.size(-1) seems to return the number of tokens in the probability distribution at each decoding step instead of dimension 0, which always has the value 1. Using the value returned from probs.size(0) causes the algorithm to think that there is only 1 possible token at each decoding step, which is not true.

Below shows the implementation of calculate_confidence() using probs.size(-1):
```python
def calculate_confidence_prob_size_minus_one(logits: List[torch.Tensor], answer_ids: torch.Tensor) -> float:
    """
    Calculate the confidence score (Δ) as specified in the paper.
    
    Args:
        logits: List of logits for each decoding step
        answer_ids: Tensor of token ids for the answer
    
    Returns:
        Confidence score (Δ)
    """
    confidence_sum = 0.0
    valid_tokens = 0
    for t, token_id in enumerate(answer_ids):
        if t >= len(logits):
            break
        token_logits = logits[t]
        probs = torch.softmax(token_logits, dim=-1)
        if probs.size(-1) > 1:
            top_2_probs, _ = torch.topk(probs, min(2, probs.size(-1)))
            
            if top_2_probs.size(-1) > 1:
                # accessing zeroth and first prob from top_2_probs in dim -1
                confidence_sum += (top_2_probs[-1][0] - top_2_probs[-1][1]).item()
            else:
                confidence_sum += 1.0  # Max confidence if there's only one token
        else:
            confidence_sum += 1.0  # Max confidence if there's only one token
        valid_tokens += 1
    
    return confidence_sum / valid_tokens if valid_tokens > 0 else 0.0
```

Below is a screenshot of a list of answer texts and their respective confidence levels, none of which are 1 which seems to be more realistic.

![image](https://github.com/user-attachments/assets/8b5734bc-6358-4cbd-a61b-de35a6bd123e)

Here is the link to the Jupyter notebook on Google Colab to replicate my test: https://colab.research.google.com/drive/1HREFUxbhnURlyU6fu6E2Kybzxnry8b53?usp=sharing

Do let me know if there are any errors in my test that resulted in the original code calculating wrong confidence levels. Thanks!

**Comment by codelion** [comment]
Hey, thanks for checking it out, can you please submit a PR it does look like a bug.
