### ISSUE TITLE
Minimal working MCTS example

### ISSUE THREAD

**Issue by RomanKoshkin** [codelion/optillm#5]
Please add a minimal example for the MCTS case. Thanks!

**Comment by codelion** [comment]
The test results has output for all the approaches, here is one for mcts from the arena hard auto - https://github.com/codelion/optillm/blob/15b7fe4e716560a033827bb4b478dacf08952b19/test_results.json#L40 

I can probably add a full log with the run showing the roll outs and intermediate steps, is that what you were looking for?

**Comment by codelion** [comment]
I added a page in the wiki showing the full run [here](https://github.com/codelion/optillm/wiki/MCTS)

**Comment by RomanKoshkin** [comment]
Thanks!
