### ISSUE TITLE
[Question]: Which paper is mcts.py based on?

### ISSUE THREAD

**Issue by RomanKoshkin** [codelion/optillm#51]
Could you tell me which paper(s) is this code https://github.com/codelion/optillm/blob/main/optillm/mcts.py based on? Thanks!

**Comment by codelion** [comment]
It is not a direct implementation of a paper but I took the inspiration from [Monte Carlo Tree Search Boosts Reasoning via Iterative Preference Learning](https://arxiv.org/abs/2405.00451). The technique in that paper for training not inference but in this library I implemented it during inference. 

It is similar to [Prover-Verifier Games improve legibility of LLM outputs
](https://arxiv.org/abs/2407.13692), that is also a technique for training but in this library it is implemented during inference.
