### ISSUE TITLE
token counting

### ISSUE THREAD

**Issue by darkacorn** [codelion/optillm#52]
for stream and non stream .. would be amazing .. specially for keeping track of i/o cost 

easy enough for non stream .. but stream is a whole other can of worms

**Comment by codelion** [comment]
Token counting is already implemented [here](https://github.com/codelion/optillm/blob/7429aec15f671749ddab560c3e4beff769fd361e/optillm.py#L331). The completion tokens you get from the proxy include the counts of all the calls made during the approach.

We also did a test of various techniques on the AIME benchmark recently to check which ones are more effective on a per token basis.  Results for that are available [here](https://github.com/codelion/optillm/discussions/31#discussioncomment-10738332)
