### ISSUE TITLE
Integration with Gemini 1.5 models

### ISSUE THREAD

**Issue by tranhoangnguyen03** [codelion/optillm#54]
Since the optillm supports OpenAI api, could it extended to support Gemini 1.5 models as well, namely Pro, Flash, and 8B. Gemini models, while not as capable as OpenAI ones at reasoning, are, instead, very fast, inexpensive, and good handling very long context.

**Comment by tranhoangnguyen03** [comment]
Already available through LiteLM. Still, it's a steep learning curve trying to setup everything at the moment; some tutorials would be highly appreciated.

**Comment by codelion** [comment]
Yes, for using gemini models, just run `python optillm.py` as usual and then set the `GOOGLE_API_KEY` and then you can call the model you want using [LitelLLM syntax](https://docs.litellm.ai/docs/providers/gemini#sample-usage). so to use `moa` with `google/gemini-1.5-flash-002` set `moa-gemini-1.5-flash-002` as model when using the client with the proxy.

I will add more tutorials in the wiki soon. Thanks.
