### ISSUE TITLE
Is there any possibility we align some interest?

### ISSUE THREAD

**Issue by femto** [codelion/optillm#57]
Hello, I'm doing minion now https://github.com/femto/minion,

a quick demo here: https://www.youtube.com/watch?v=-LW7TCMUfLs&t=33s,
basically I want to do is it can handle arbitrary type of queries, math, coding, qa,
long novel writing, open world exploration, just throw problems at it,
you can think of it kind like a baby AGI.

Is there any chance that we align some interest?

**Comment by codelion** [comment]
Hi @femto I had a quick look at your repo, It looks interesting. It will be good to see some results on standard benchmarks to compare the difference between the base model.

I have taken a slightly different approach and trained a bert style classifier (https://huggingface.co/codelion/optillm-bert-uncased) that can be used to route the request to the best approach. It is implemented in the router plugin - https://github.com/codelion/optillm/blob/main/optillm/plugins/router_plugin.py

With plugin support it is now possible to script anything with optillm proxy so one possibility could be to just add minion as a plugin and then it can do the exploration.
