### ISSUE TITLE
When I tried the optillm with my own openai API compatible hosted model I get this error

### ISSUE THREAD

**Issue by shamanez** [codelion/optillm#58]
I used "no_key"

`error': "Error code: 401 - {'error': {'message': 'Incorrect API key provided: no_key. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"`

**Comment by codelion** [comment]
Did you run with `-base_url http://your_api_end_point/v1` ? The error suggests it is still going to the default endpoint from OpenAI.

**Comment by shamanez** [comment]
Yup.  Actually, we were able to sort it out by passing an api_key similar to the openai_api key. 

Btw this is some amazing work!

**Comment by codelion** [comment]
Glad it worked out!

**Comment by shamanez** [comment]
The problem was in some sort of an encryption thing. We just created a dummy API key, which has exactly the same pattern as a real openAI api key.

**Comment by codelion** [comment]
Oh, I think it just has to be pretending with “sk-“ because I check for that [here](https://github.com/codelion/optillm/blob/193ab3c4d54f5f2e2c47525293bd7827b609675f/optillm.py#L300) to ensure it is a valid OpenAI key.

**Comment by shamanez** [comment]
True. Might be good to change the documentation for the future ref
