### ISSUE TITLE
Request for Reference Citations for CoT Prompting Methods

### ISSUE THREAD

**Issue by qsunyuan** [codelion/optillm#64]
Hello,

Thank you for providing such a comprehensive library on Chain-of-Thought (CoT) reasoning. I really appreciate the work you've done! I was wondering if it would be possible to include references to specific academic papers that correspond to each method in the library (or code comment). 

For example, in this link https://github.com/codelion/optillm?tab=readme-ov-file#references, the reference for _Self-Consistency CoT_ could be linked to the paper _Self-Consistency Improves Chain of Thought Reasoning in Language Models_.

Thanks again for your great work!

Best regards.

**Comment by codelion** [comment]
Thanks for the suggestion, I have fixed it in https://github.com/codelion/optillm/commit/5d471d1c0afc82430d766e94e9ff22eac9f3e9e2
