### ISSUE TITLE
Feature: easy to add new approaches

### ISSUE THREAD

**Issue by ErykCh** [codelion/optillm#72]
Hi,

I don't know if this is in the path of development you are planning. But it would be nice if it was easy to add new approaches.

1 adding new user approaches
2 easy to configure new approaches
3 easy to configure approaches via chat

1. Adding a new directory, so that from the docker level you can map it to your directory on the disk. And you won't have to manually add it to the image.

docker-compose.yml
```
services:
  optillm:
    volumes:
    - ./approaches:optillm/custom
```

In the approaches directory you add, for example:
o1.py

Automatically o1 is added to known_approaches in optillm.py and you can use it like any other.

2. Maybe it's not the best solution, but I think it's quite easy to solve. When o1.py is called, all properties are passed to it (whether from environment or from program invocation),
 for example envrionment
   OPTILLM_O1_MYSETTING=myvalue
 from program invocation
    --o1-mysetting=myvalue

and then o1.py gets dictionary key value
and it will get mysetting=myvalue
custom code than can use it

3. Possibility to provide settings in conversation.
I can add in conversation:
<optillm_approach>mcts|o1</optillm_approach>
<optillm_settings>mcts-depth=3, o1-mysetting=myvalue</optillm_settings>

and these settings overwrite those provided when starting the program or from the environment.

I can also try to add these functionalities to your code myself if you allow me.

**Comment by codelion** [comment]
You can already add any new approaches or any function using the plugins, just put your o1.py file in the plugins directory and it will be loaded at runtime. You can see the implementation of existing plugins to see how it works - https://github.com/codelion/optillm/tree/main/optillm/plugins

You just need to have a `SLUG` and method `def run(system_prompt: str, initial_query: str, client, model: str) -> Tuple[str, int]:` when someone called the approach with `SLUG` name the `run` method on the corresponding plugin is called.
